
export const EVENT_SELECT_EMAIL = 'EVENT_SELECT_EMAIL'
export const EVENT_DELETE_EMAIL = 'EVENT_DELETE_EMAIL'
export const EVENT_FILTER_EMAILS = 'EVENT_FILTER_EMAILS'
export const EVENT_SORT_TITLE = 'EVENT_SORT_TITLE'
export const EVENT_SORT_DATE = 'EVENT_SORT_DATE'


export const eventBus = new Vue();

